---
title: "Thesis Analysis"
output: html_document
date: "2023-08-24"
editor_options: 
  chunk_output_type: console
---
  

```{r setup, include=FALSE}
library(tidyverse)
library(dygraphs)
library(lubridate)
library(xts)
library(knitr)
```

```{r data, echo=FALSE, warning=FALSE, message=FALSE}
# load the data for different parameters
# CSI data
files <- list.files(path = "../../data/sleep_lab/clean_data/esp/right", pattern = "*.CSV", full.names = T)
full_data <- data_frame()
for (file in files) {
  overflow_index <- 57214
  data <- read_csv(file)
  data$local_timestamp[overflow_index:nrow(data)] <- data$local_timestamp[overflow_index:nrow(data)] + 4294967295
  
  file_type <- tools::file_path_sans_ext(basename(file))

  data <- data %>% mutate(pose = "none", condition = "none", filename = file_type)
  # assign the conditions manually
  # order of poses: back, left, stomach, right
  # order of conditions: without blanket, with blanket
  data$pose[14927:19242] = "back"
  data$condition[14927:19242] = "open"
  
  data$pose[25470:28543] = "left"
  data$condition[25401:28543] = "open"
  
  data$pose[34215:36099] = "stomach"
  data$condition[34215:36099] = "open"
  
  data$pose[39726:44131] = "right"
  data$condition[39726:44131] = "open"
  
  
  data$pose[47284:51867] = "back"
  data$condition[47284:51867] = "blanket"
  
  data$pose[55271:57690] = "left"
  data$condition[55271:57690] = "blanket"
  
  data$pose[60798:61955] = "stomach"
  data$condition[60798:61955] = "blanket"
  
  data$pose[64565:69201] = "right"
  data$condition[64565:69201] = "blanket"

  full_data <- rbind(full_data, data)
}

plot <- full_data  %>% filter(filename=="CSI") %>% mutate(time=local_timestamp/1000000) %>% select(time, sti) 
p <- dygraph(plot, xlab = "time (in seconds)", ylab = "STI") %>%
  dyOptions(drawPoints = TRUE, pointSize = 2) %>%
  dyRangeSelector()

show(p)

output_file <- "time_series_plot.html"
#library(webshot)
# Export the dygraph plot as a PDF image
htmlwidgets::saveWidget(p, file = output_file)


```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# load the data from the reference device
# Define the main directory path
main_directory <- "../../data/sleep_lab/clean_data/gt"

# List all subdirectories (conditions) in the main directory
condition_dirs <- list.dirs(main_directory, full.names = FALSE, recursive = FALSE)

# Define skip values for each CSV file type (adjust as needed)
skip_values <- c(AF = 5, `ECG II` = 7, `Herzfrequenz Kurve` = 5, `RIP Abdom` = 7, `RIP Thora` = 7)

# Initialize an data frame
data_frames <- data_frame()

# Loop through condition directories
for (condition_dir in condition_dirs) {
  # List all subdirectories (poses) in the current condition directory
  pose_dirs <- list.dirs(file.path(main_directory, condition_dir), full.names = FALSE, recursive = FALSE)
  
  # Loop through pose directories
  for (pose_dir in pose_dirs) {
    # List all CSV files in the current pose directory
    csv_files <- list.files(file.path(main_directory, condition_dir, pose_dir), pattern = "txt", full.names = TRUE)
  
    # Loop through CSV files and read them with the corresponding skip value
    for (csv_file in csv_files) {
      file_type <- tools::file_path_sans_ext(basename(csv_file))
      skip_value <- skip_values[file_type]
      
      df <- read_delim(csv_file, delim = ";", skip = skip_value, col_names = FALSE, col_types = "cc")  # Adjust read.delim options as needed
      df$Condition <- condition_dir
      df$Pose <- pose_dir
      df$type <- file_type
      
      # Add to the large data frame
      data_frames <- bind_rows(data_frames, df)
    }
  }
}

colnames(data_frames) <- c("time", "value", "condition", "pose", "type")
data_frames$time <- gsub(",", ".", data_frames$time)
# Create individual data frames for each file type 
full_gt_breathing_rate <- data_frames %>% filter(type == "AF")
full_gt_ecg <- data_frames %>% filter(type == "ECG II")
full_gt_heart_rate <- data_frames %>% filter(type == "Herzfrequenz Kurve")
full_gt_breath_a <- data_frames %>% filter(type == "RIP Abdom")
full_gt_breath_t <- data_frames %>% filter(type == "RIP Thora")


stop_times <- c(as.POSIXct("1970-01-01 00:04:35.000", "UTC"), 
                 as.POSIXct("1970-01-01 00:04:57.000", "UTC"), 
                 as.POSIXct("1970-01-01 00:02:01.000", "UTC"), 
                 as.POSIXct("1970-01-01 00:04:52.000", "UTC"), 
                 as.POSIXct("1970-01-01 00:04:51.000", "UTC"), 
                 as.POSIXct("1970-01-01 00:04:49.000", "UTC"), 
                 as.POSIXct("1970-01-01 00:04:52.000", "UTC"), 
                 as.POSIXct("1970-01-01 00:05:02.000", "UTC"))
poses <- c("back", "left", "stomach", "right", "back", "left", "stomach", "right")
conditions <- c("open", "open", "open", "open", "blanket", "blanket", "blanket", "blanket")
times <- data_frame(stop_times, poses, conditions)
```

<!-- use this -->
# Comparison plots for all parameters showing all conditions
```{r, echo=FALSE, warning=FALSE, message=FALSE}
complete_breath_results = data_frame()
complete_heart_results = data_frame()

for (c in c("open", "blanket")) {
  for (p in c("back", "left", "stomach", "right")) {
    data <- full_data %>% filter(pose == p & condition == c & filename == "CSI")
    breath_features <- data$breath_features
    breath_features <- data.frame(breath_features)
    
    breath_features <- breath_features %>%
      mutate(breath_features = substr(breath_features, 2, nchar(breath_features) - 1)) %>%
      mutate(breath_features = strsplit(breath_features, " ")) %>%
      mutate(breath_features = lapply(breath_features, function(x) as.numeric(x)))
    
    breath_features <- data.frame(matrix(unlist(breath_features$breath_features), ncol = 19, byrow = TRUE))
    colnames(breath_features) <- c("instantaneous_peak_rate","instantaneous_valley_rate","mean_peak_rate_over_window","mean_valley_rate_over_window","fft_rate_over_window","variance_of_peak_rate_in_window","variance_of_valley_rate_in_window","mean_up_stroke_length","mean_down_stroke_length","up_stroke_length_variance","down_stroke_length_variance","up_to_down_length_ratio","fractional_up_stroke_time","mean_up_stroke_amplitude","mean_down_stroke_amplitude","up_stroke_amplitude_variance","down_stroke_amplitude_variance","up_to_down_amplitude_ratio","fractional_up_stroke_amplitude")
    
    data$local_timestamp = data$local_timestamp - data$local_timestamp[1]
    breath_features <- cbind(breath_features, data$local_timestamp)
    breath_features <- breath_features %>% rename(time = `data$local_timestamp`) 
    breath_features <- breath_features %>% mutate(time = as.POSIXct(breath_features$time/1000000, "UTC", origin = "1970-01-01"))
    
    heart_features <- data$heart_features
    heart_features <- data.frame(heart_features)
    
    heart_features <- heart_features %>%
      mutate(heart_features = substr(heart_features, 2, nchar(heart_features) - 1)) %>%
      mutate(heart_features = strsplit(heart_features, " ")) %>%
      mutate(heart_features = lapply(heart_features, function(x) as.numeric(x)))
    
    heart_features <- data.frame(matrix(unlist(heart_features$heart_features), ncol = 19, byrow = TRUE))
    colnames(heart_features) <- c("instantaneous_peak_rate","instantaneous_valley_rate","mean_peak_rate_over_window","mean_valley_rate_over_window","fft_rate_over_window","variance_of_peak_rate_in_window","variance_of_valley_rate_in_window","mean_up_stroke_length","mean_down_stroke_length","up_stroke_length_variance","down_stroke_length_variance","up_to_down_length_ratio","fractional_up_stroke_time","mean_up_stroke_amplitude","mean_down_stroke_amplitude","up_stroke_amplitude_variance","down_stroke_amplitude_variance","up_to_down_amplitude_ratio","fractional_up_stroke_amplitude")
    
    heart_features <- cbind(heart_features, data$local_timestamp)
    heart_features <- heart_features %>% rename(time = `data$local_timestamp`) 
    heart_features <- heart_features %>% mutate(time = as.POSIXct(heart_features$time/1000000, "UTC", origin = "1970-01-01"))
    
    
    gt_breathing_rate <- full_gt_breathing_rate %>% filter(pose == p & condition == c)
    gt_breathing_rate$time <- as.POSIXct(paste("1970-01-01", gt_breathing_rate$time), tz = "UTC")
    gt_breathing_rate$time <- gt_breathing_rate$time - (gt_breathing_rate$time[1] - as.POSIXct("1970-01-01 00:00:00.000", "UTC"))
    gt_breathing_rate <- gt_breathing_rate %>% select(!type) %>% mutate(value = as.numeric(value))
    
    breath_results <- breath_features %>%
      full_join(gt_breathing_rate, by = "time")  %>%
      arrange(time)
    breath_results$value <- zoo::na.locf(breath_results$value, na.rm = F)
    breath_results$condition <- zoo::na.locf(breath_results$condition, na.rm = F)
    breath_results$pose <- zoo::na.locf(breath_results$pose, na.rm = F)
    breath_results <- breath_results %>% filter(!is.na(fft_rate_over_window))
    # remove initial rows where the reference is 0
    breath_results <- breath_results %>% filter(value != 0)
    
    # get the error and absolute error for breathing and heart rate
    breath_results <- breath_results %>% select(instantaneous_peak_rate, fft_rate_over_window, mean_peak_rate_over_window, value, time, condition, pose)
    colnames(breath_results) <- c("instantaneous_peak_rate", "fft_rate_over_window", "mean_peak_rate_over_window", "gt_breathing_rate", "time", "condition", "pose")
    
    
    gt_heart_rate <- full_gt_heart_rate %>% filter(pose == p & condition == c)
    gt_heart_rate$time <- as.POSIXct(paste("1970-01-01", gt_heart_rate$time), tz = "UTC")
    gt_heart_rate$time <- gt_heart_rate$time - (gt_heart_rate$time[1] - as.POSIXct("1970-01-01 00:00:00.000", "UTC"))
    gt_heart_rate <- gt_heart_rate %>% select(!type) %>% mutate(value = as.numeric(value))
    
    heart_results <- heart_features %>%
      full_join(gt_heart_rate, by = "time")  %>%
      arrange(time)
    heart_results$value <- zoo::na.locf(heart_results$value, na.rm = F)
    heart_results$condition <- zoo::na.locf(heart_results$condition, na.rm = F)
    heart_results$pose <- zoo::na.locf(heart_results$pose, na.rm = F)
    heart_results <- heart_results %>% filter(!is.na(fft_rate_over_window))
    # remove initial rows where the reference is 0
    heart_results <- heart_results %>% filter(value != 0)
    
    heart_results <- heart_results %>% select(instantaneous_peak_rate, fft_rate_over_window, mean_peak_rate_over_window, value, time, condition, pose)
    colnames(heart_results) <- c("instantaneous_peak_rate", "fft_rate_over_window", "mean_peak_rate_over_window", "gt_heart_rate", "time", "condition", "pose")
    
    breath_results <- breath_results %>%
      mutate(fft_error = fft_rate_over_window - gt_breathing_rate,
             abs_fft_error = abs(fft_rate_over_window - gt_breathing_rate),
             error = mean_peak_rate_over_window - gt_breathing_rate,
             abs_error = abs(mean_peak_rate_over_window - gt_breathing_rate),
             i_error = instantaneous_peak_rate - gt_breathing_rate,
             abs_i_error = abs(instantaneous_peak_rate - gt_breathing_rate))
    
    heart_results <- heart_results %>%
      mutate(fft_error = fft_rate_over_window - gt_heart_rate,
             abs_fft_error = abs(fft_rate_over_window - gt_heart_rate),
             error = mean_peak_rate_over_window - gt_heart_rate,
             abs_error = abs(mean_peak_rate_over_window - gt_heart_rate),
             i_error = instantaneous_peak_rate - gt_heart_rate,
             abs_i_error = abs(instantaneous_peak_rate - gt_heart_rate))
    
    start_time <- as.POSIXct("1970-01-01 00:00:15.000", "UTC")
    r <- times %>% filter(poses == p, conditions == c)
    stop_time <- r$stop_times
    breath_results <- breath_results %>% filter(time > start_time & time < stop_time)
    heart_results <- heart_results %>% filter(time > start_time & time < stop_time)
    
    complete_breath_results <- rbind(complete_breath_results, breath_results)
    complete_heart_results <- rbind(complete_heart_results, heart_results)
  }
}

###########################################################
##################    Pose    
###########################################################
# plot the results
to_plot <- complete_breath_results %>% select(fft_error, abs_fft_error, error, abs_error, pose) %>% pivot_longer(cols = c("fft_error", "abs_fft_error", "error", "abs_error"), names_to = "error_type", values_to = "values") %>% group_by(error_type, pose)
p <- to_plot %>% ggplot() +
  geom_violin(aes(y=values, x=error_type, fill = pose), width = 0.75, linewidth=0.2) +
  theme_light()+
  labs(fill = "Pose")+
  ylab("Error (in bpm)")+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(),
        legend.justification = c(1, 1), 
        legend.position = c(1, 1))+
  scale_x_discrete(labels=c("abs_error"="absolute peak rate error", "abs_fft_error"="absolute fft rate error", "error"="peak rate error", "fft_error"="fft rate error")) +
  scale_fill_manual(values=c("back"="#D8F7FF", "left"="#FFCEFF", "stomach"="#AEFFAE", "right"="#FFEED0"))
 
p 
ggsave("PoseBreath.pdf", plot = p, device = "pdf", width = 16.18, height = 10, units = "cm")

# print the summary
t <- to_plot %>% summarise(
  minimum = min(values),
  mean = mean(values),
  median = median(values),
  maximum = max(values))

kable(t, format = "latex", caption = "Summary statistics of the different breathing errors for the different poses", label = "tab:poses", align = "c")

# plot the results
to_plot <-  complete_heart_results %>% select(fft_error, abs_fft_error, error, abs_error, pose) %>% pivot_longer(cols = c("fft_error", "abs_fft_error", "error", "abs_error"), names_to = "error_type", values_to = "values") %>% group_by(error_type, pose)
p<-to_plot %>% ggplot() +
  geom_violin(aes(y=values, x=error_type, fill = pose), width = 0.75, linewidth=0.2) +
  theme_light()+
  labs(fill = "Pose")+
  ylab("Error (in bpm)")+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(),
        legend.justification = c(1, 1), 
        legend.position = c(1, 1))+
  scale_x_discrete(labels=c("abs_error"="absolute peak rate error", "abs_fft_error"="absolute fft rate error", "error"="peak rate error", "fft_error"="fft rate error")) +
  scale_fill_manual(values=c("back"="#D8F7FF", "left"="#FFCEFF", "stomach"="#AEFFAE", "right"="#FFEED0"))

p
ggsave("PoseHeart.pdf", plot = p, device = "pdf", width = 16.18, height = 10, units = "cm")

# print the summary
t<-to_plot %>% summarise(
  minimum = min(values),
  mean = mean(values),
  median = median(values),
  maximum = max(values))
kable(t, format = "latex", caption = "Summary statistics of the different heart rate errors for the different poses", label = "tab:poses", align = "c")



###########################################################
##################    Condition    
###########################################################
# plot the results
to_plot <- complete_breath_results %>% select(fft_error, abs_fft_error, error, abs_error, condition) %>% pivot_longer(cols = c("fft_error", "abs_fft_error", "error", "abs_error"), names_to = "error_type", values_to = "values") %>% group_by(error_type, condition)
p<-to_plot %>% ggplot() +
  geom_violin(aes(y=values, x=error_type, fill = condition), linewidth=0.2) +
  theme_light()+
  labs(fill = "Condition")+
  ylab("Error (in bpm)")+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(),
        legend.justification = c(1, 1), 
        legend.position = c(1, 1))+
  scale_x_discrete(labels=c("abs_error"="absolute peak rate error", "abs_fft_error"="absolute fft rate error", "error"="peak rate error", "fft_error"="fft rate error")) +
  scale_fill_manual(values=c("open"="#D3D3D3", "blanket"="#555555"))
  
p
ggsave("ConditionBreath.pdf", plot = p, device = "pdf", width = 16.18, height = 10, units = "cm")

# print the summary
t<-to_plot %>% summarise(
  minimum = min(values),
  mean = mean(values),
  median = median(values),
  maximum = max(values))

kable(t, format = "latex", caption = "Summary statistics of the different breathing rate errors for the different conditions", label = "tab:conditions_breath", align = "c")


# plot the results
to_plot <-  complete_heart_results %>% select(fft_error, abs_fft_error, error, abs_error, condition) %>% pivot_longer(cols = c("fft_error", "abs_fft_error", "error", "abs_error"), names_to = "error_type", values_to = "values") %>% group_by(error_type, condition)
p <- to_plot %>% ggplot() +
  geom_violin(aes(y=values, x=error_type, fill = condition), linewidth=0.2) +
  theme_light()+
  labs(fill = "Condition")+
  ylab("Error (in bpm)")+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(),
        legend.justification = c(1, 1), 
        legend.position = c(1, 1))+
  scale_x_discrete(labels=c("abs_error"="absolute peak rate error", "abs_fft_error"="absolute fft rate error", "error"="peak rate error", "fft_error"="fft rate error")) +
  scale_fill_manual(values=c("open"="#D3D3D3", "blanket"="#555555"))

p
ggsave("ConditionHeart.pdf", plot = p, device = "pdf", width = 16.18, height = 10, units = "cm")

# print the summary
t<-to_plot %>% summarise(
  minimum = min(values),
  mean = mean(values),
  median = median(values),
  maximum = max(values))
kable(t, format = "latex", caption = "Summary statistics of the different heart rate errors for the different conditions", label = "tab:conditions_heart", align = "c")

###########################################################
##################    Pose + Open    
###########################################################
# plot the results
to_plot <- complete_breath_results %>% filter(condition=="open") %>% select(fft_error, abs_fft_error, error, abs_error, pose) %>% pivot_longer(cols = c("fft_error", "abs_fft_error", "error", "abs_error"), names_to = "error_type", values_to = "values") %>% group_by(error_type, pose)
p<-to_plot %>% ggplot() +
  geom_violin(aes(y=values, x=error_type, fill = pose), width = 0.75, linewidth=0.2) +
  theme_light()+
  labs(fill = "Pose")+
  ylab("Error (in bpm)")+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(),
        legend.justification = c(1, 1), 
        legend.position = c(1, 1))+
  scale_x_discrete(labels=c("abs_error"="absolute peak rate error", "abs_fft_error"="absolute fft rate error", "error"="peak rate error", "fft_error"="fft rate error")) +
  scale_fill_manual(values=c("back"="#D8F7FF", "left"="#FFCEFF", "stomach"="#AEFFAE", "right"="#FFEED0"))
  
p
ggsave("OpenPoseBreath.pdf", plot = p, device = "pdf", width = 16.18, height = 10, units = "cm")

# print the summary
t<-to_plot %>% summarise(
  minimum = min(values),
  mean = mean(values),
  median = median(values),
  maximum = max(values))

kable(t, format = "latex", caption = "Summary statistics of the different breathing rate errors for the different poses during the open condition", label = "tab:poses_open_heart", align = "c")

# plot the results
to_plot <-  complete_heart_results %>% filter(condition=="open") %>% select(fft_error, abs_fft_error, error, abs_error, pose) %>% pivot_longer(cols = c("fft_error", "abs_fft_error", "error", "abs_error"), names_to = "error_type", values_to = "values") %>% group_by(error_type, pose)
p<-to_plot %>% ggplot() +
  geom_violin(aes(y=values, x=error_type, fill = pose), width = 0.75, linewidth=0.2) +
  theme_light()+
  labs(fill = "pose")+
  ylab("Error (in bpm)")+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(),
        legend.justification = c(1, 1), 
        legend.position = c(1, 1))+
  scale_x_discrete(labels=c("abs_error"="absolute peak rate error", "abs_fft_error"="absolute fft rate error", "error"="peak rate error", "fft_error"="fft rate error")) +
  scale_fill_manual(values=c("back"="#D8F7FF", "left"="#FFCEFF", "stomach"="#AEFFAE", "right"="#FFEED0"))

p
ggsave("OpenPoseHeart.pdf", plot = p, device = "pdf", width = 16.18, height = 10, units = "cm")

# print the summary
t<-to_plot %>% summarise(
  minimum = min(values),
  mean = mean(values),
  median = median(values),
  maximum = max(values))

kable(t, format = "latex", caption = "Summary statistics of the different heart rate errors for the different poses during the open condition", label = "tab:poses_open_heart", align = "c")


###########################################################
##################    Pose + Blanket    
###########################################################
# plot the results
to_plot <- complete_breath_results %>% filter(condition=="blanket") %>% select(fft_error, abs_fft_error, error, abs_error, pose) %>% pivot_longer(cols = c("fft_error", "abs_fft_error", "error", "abs_error"), names_to = "error_type", values_to = "values") %>% group_by(error_type, pose)
p<-to_plot %>% ggplot() +
  geom_violin(aes(y=values, x=error_type, fill = pose), width = 0.75, linewidth=0.2) +
  theme_light()+
  labs(fill = "Pose")+
  ylab("Error (in bpm)")+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(),
        legend.justification = c(1, 1), 
        legend.position = c(1, 1))+
  scale_x_discrete(labels=c("abs_error"="absolute peak rate error", "abs_fft_error"="absolute fft rate error", "error"="peak rate error", "fft_error"="fft rate error")) +
  scale_fill_manual(values=c("back"="#D8F7FF", "left"="#FFCEFF", "stomach"="#AEFFAE", "right"="#FFEED0"))
  
p
ggsave("BlanketPoseBreath.pdf", plot = p, device = "pdf", width = 16.18, height = 10, units = "cm")

# print the summary
t <- to_plot %>% summarise(
  minimum = min(values),
  mean = mean(values),
  median = median(values),
  maximum = max(values))

kable(t, format = "latex", caption = "Summary statistics of the different breathing rate errors for the different poses during the blanket condition", label = "tab:poses_blanket_breath", align = "c")


# plot the results
to_plot <-  complete_heart_results %>% filter(condition=="blanket") %>% select(fft_error, abs_fft_error, error, abs_error, pose) %>% pivot_longer(cols = c("fft_error", "abs_fft_error", "error", "abs_error"), names_to = "error_type", values_to = "values") %>% group_by(error_type, pose)
p<-to_plot %>% ggplot() +
  geom_violin(aes(y=values, x=error_type, fill = pose), width = 0.75, linewidth=0.2) +
  theme_light()+
  labs(fill = "pose")+
  ylab("Error (in bpm)")+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(),
        legend.justification = c(1, 1), 
        legend.position = c(1, 1))+
  scale_x_discrete(labels=c("abs_error"="absolute peak rate error", "abs_fft_error"="absolute fft rate error", "error"="peak rate error", "fft_error"="fft rate error")) +
  scale_fill_manual(values=c("back"="#D8F7FF", "left"="#FFCEFF", "stomach"="#AEFFAE", "right"="#FFEED0"))

p
ggsave("BlanketPoseHeart.pdf", plot = p, device = "pdf", width = 16.18, height = 10, units = "cm")

# print the summary
t<-to_plot %>% summarise(
  minimum = min(values),
  mean = mean(values),
  median = median(values),
  maximum = max(values))

kable(t, format = "latex", caption = "Summary statistics of the different heart rate errors for the different poses during the blanket condition", label = "tab:poses_blanket_heart", align = "c")
```

<!-- use this -->

## Breathing and heart rate error across all conditions - effect of different system components
```{r}
complete_breath_results = data_frame()
complete_heart_results = data_frame()

for (c in c("open", "blanket")) {
  for (p in c("back", "left", "stomach", "right")) {
    data <- full_data %>% filter(pose == p & condition == c)
    breath_features <- data$breath_features
    breath_features <- data.frame(breath_features)
    
    breath_features <- breath_features %>%
      mutate(breath_features = substr(breath_features, 2, nchar(breath_features) - 1)) %>%
      mutate(breath_features = strsplit(breath_features, " ")) %>%
      mutate(breath_features = lapply(breath_features, function(x) as.numeric(x)))
    
    breath_features <- data.frame(matrix(unlist(breath_features$breath_features), ncol = 19, byrow = TRUE))
    colnames(breath_features) <- c("instantaneous_peak_rate","instantaneous_valley_rate","mean_peak_rate_over_window","mean_valley_rate_over_window","fft_rate_over_window","variance_of_peak_rate_in_window","variance_of_valley_rate_in_window","mean_up_stroke_length","mean_down_stroke_length","up_stroke_length_variance","down_stroke_length_variance","up_to_down_length_ratio","fractional_up_stroke_time","mean_up_stroke_amplitude","mean_down_stroke_amplitude","up_stroke_amplitude_variance","down_stroke_amplitude_variance","up_to_down_amplitude_ratio","fractional_up_stroke_amplitude")
    
    data$local_timestamp = data$local_timestamp - data$local_timestamp[1]
    breath_features <- cbind(breath_features, data$local_timestamp, data$filename)
    breath_features <- breath_features %>% rename(time = `data$local_timestamp`, filename = `data$filename`) 
    breath_features <- breath_features %>% mutate(time = as.POSIXct(breath_features$time/1000000, "UTC", origin = "1970-01-01"))
    
    heart_features <- data$heart_features
    heart_features <- data.frame(heart_features)
    
    heart_features <- heart_features %>%
      mutate(heart_features = substr(heart_features, 2, nchar(heart_features) - 1)) %>%
      mutate(heart_features = strsplit(heart_features, " ")) %>%
      mutate(heart_features = lapply(heart_features, function(x) as.numeric(x)))
    
    heart_features <- data.frame(matrix(unlist(heart_features$heart_features), ncol = 19, byrow = TRUE))
    colnames(heart_features) <- c("instantaneous_peak_rate","instantaneous_valley_rate","mean_peak_rate_over_window","mean_valley_rate_over_window","fft_rate_over_window","variance_of_peak_rate_in_window","variance_of_valley_rate_in_window","mean_up_stroke_length","mean_down_stroke_length","up_stroke_length_variance","down_stroke_length_variance","up_to_down_length_ratio","fractional_up_stroke_time","mean_up_stroke_amplitude","mean_down_stroke_amplitude","up_stroke_amplitude_variance","down_stroke_amplitude_variance","up_to_down_amplitude_ratio","fractional_up_stroke_amplitude")
    
    heart_features <- cbind(heart_features, data$local_timestamp, data$filename)
    heart_features <- heart_features %>% rename(time = `data$local_timestamp`, filename = `data$filename`) 
    heart_features <- heart_features %>% mutate(time = as.POSIXct(heart_features$time/1000000, "UTC", origin = "1970-01-01"))
    
    
    gt_breathing_rate <- full_gt_breathing_rate %>% filter(pose == p & condition == c)
    gt_breathing_rate$time <- as.POSIXct(paste("1970-01-01", gt_breathing_rate$time), tz = "UTC")
    gt_breathing_rate$time <- gt_breathing_rate$time - (gt_breathing_rate$time[1] - as.POSIXct("1970-01-01 00:00:00.000", "UTC"))
    gt_breathing_rate <- gt_breathing_rate %>% select(!type) %>% mutate(value = as.numeric(value))
    
    breath_results <- breath_features %>%
      full_join(gt_breathing_rate, by = "time")  %>%
      arrange(time)
    breath_results$value <- zoo::na.locf(breath_results$value, na.rm = F)
    breath_results$condition <- zoo::na.locf(breath_results$condition, na.rm = F)
    breath_results$pose <- zoo::na.locf(breath_results$pose, na.rm = F)
    breath_results <- breath_results %>% filter(!is.na(fft_rate_over_window))
    # remove initial rows where the reference is 0
    breath_results <- breath_results %>% filter(value != 0)
    
    # get the error and absolute error for breathing and heart rate
    breath_results <- breath_results %>% select(instantaneous_peak_rate, fft_rate_over_window, mean_peak_rate_over_window, value, time, condition, pose, filename)
    colnames(breath_results) <- c("instantaneous_peak_rate", "fft_rate_over_window", "mean_peak_rate_over_window", "gt_breathing_rate", "time", "condition", "pose", "filename")
    
    
    gt_heart_rate <- full_gt_heart_rate %>% filter(pose == p & condition == c)
    gt_heart_rate$time <- as.POSIXct(paste("1970-01-01", gt_heart_rate$time), tz = "UTC")
    gt_heart_rate$time <- gt_heart_rate$time - (gt_heart_rate$time[1] - as.POSIXct("1970-01-01 00:00:00.000", "UTC"))
    gt_heart_rate <- gt_heart_rate %>% select(!type) %>% mutate(value = as.numeric(value))
    
    heart_results <- heart_features %>%
      full_join(gt_heart_rate, by = "time")  %>%
      arrange(time)
    heart_results$value <- zoo::na.locf(heart_results$value, na.rm = F)
    heart_results$condition <- zoo::na.locf(heart_results$condition, na.rm = F)
    heart_results$pose <- zoo::na.locf(heart_results$pose, na.rm = F)
    heart_results <- heart_results %>% filter(!is.na(fft_rate_over_window))
    # remove initial rows where the reference is 0
    heart_results <- heart_results %>% filter(value != 0)
    
    heart_results <- heart_results %>% select(instantaneous_peak_rate, fft_rate_over_window, mean_peak_rate_over_window, value, time, condition, pose, filename)
    colnames(heart_results) <- c("instantaneous_peak_rate", "fft_rate_over_window", "mean_peak_rate_over_window", "gt_heart_rate", "time", "condition", "pose", "filename")
    
    breath_results <- breath_results %>%
      mutate(fft_error = fft_rate_over_window - gt_breathing_rate,
             abs_fft_error = abs(fft_rate_over_window - gt_breathing_rate),
             error = mean_peak_rate_over_window - gt_breathing_rate,
             abs_error = abs(mean_peak_rate_over_window - gt_breathing_rate),
             i_error = instantaneous_peak_rate - gt_breathing_rate,
             abs_i_error = abs(instantaneous_peak_rate - gt_breathing_rate))
    
    heart_results <- heart_results %>%
      mutate(fft_error = fft_rate_over_window - gt_heart_rate,
             abs_fft_error = abs(fft_rate_over_window - gt_heart_rate),
             error = mean_peak_rate_over_window - gt_heart_rate,
             abs_error = abs(mean_peak_rate_over_window - gt_heart_rate),
             i_error = instantaneous_peak_rate - gt_heart_rate,
             abs_i_error = abs(instantaneous_peak_rate - gt_heart_rate))
    
    start_time <- as.POSIXct("1970-01-01 00:00:15.000", "UTC")
    r <- times %>% filter(poses == p, conditions == c)
    stop_time <- r$stop_times
    breath_results <- breath_results %>% filter(time > start_time & time < stop_time)
    heart_results <- heart_results %>% filter(time > start_time & time < stop_time)
    
    complete_breath_results <- rbind(complete_breath_results, breath_results)
    complete_heart_results <- rbind(complete_heart_results, heart_results)
  }
}

# plot the results
to_plot <- breath_results %>% select(fft_error, abs_fft_error, error, abs_error, filename) %>% pivot_longer(cols = c("fft_error", "abs_fft_error", "error", "abs_error"), names_to = "error_type", values_to = "values") %>% group_by(filename, error_type)
p<-to_plot %>% ggplot() +
  geom_violin(aes(y=values, x=error_type, fill = filename), width = 0.75, linewidth=0.2) +
  theme_light()+
  labs(fill = "Parameter variant")+
  ylab("Error (in bpm)")+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(),
        legend.justification = c(1, 1), 
        legend.position = c(1, 1),
        legend.title=element_text(size=8), 
        legend.text=element_text(size=7))+
  scale_x_discrete(labels=c("abs_error"="absolute peak rate error", "abs_fft_error"="absolute fft rate error", "error"="peak rate error", "fft_error"="fft rate error")) +
  scale_fill_brewer(palette="Set3", labels=c("CSI"="default", "no_amp_criterion"="no amplitude criterion", "no_hampel"="no Hampel filter", "removing_static"="removing static component", "Sc_selection"="subcarrier selection"))

p
ggsave("ComponentsBreath.pdf", plot = p, device = "pdf", width = 16.18, height = 10, units = "cm")


# print the summary
t<-to_plot %>% summarise(
  minimum = min(values),
  mean = mean(values),
  median = median(values),
  maximum = max(values))

kable(t, format = "latex", caption = "Summary statistics of the different breathing rate errors for the different system settings", label = "tab:components_breath", align = "c")

# plot the results
to_plot <-  heart_results %>% select(fft_error, abs_fft_error, error, abs_error, filename) %>% pivot_longer(cols = c("fft_error", "abs_fft_error", "error", "abs_error"), names_to = "error_type", values_to = "values") %>% group_by(filename, error_type)
p<-to_plot %>% ggplot() +
  geom_violin(aes(y=values, x=error_type, fill = filename), width = 0.75, linewidth=0.2) +
  theme_light()+
  labs(fill = "Parameter variant")+
  ylab("Error (in bpm)")+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(),
        legend.justification = c(1, 1), 
        legend.position = c(1, 1),
        legend.title=element_text(size=8), 
        legend.text=element_text(size=7))+
  scale_x_discrete(labels=c("abs_error"="absolute peak rate error", "abs_fft_error"="absolute fft rate error", "error"="peak rate error", "fft_error"="fft rate error")) +
  scale_fill_brewer(palette="Set3", labels=c("CSI"="default", "no_amp_criterion"="no amplitude criterion", "no_hampel"="no Hampel filter", "removing_static"="removing static component", "Sc_selection"="subcarrier selection"))

p
ggsave("ComponentsHeart.pdf", plot = p, device = "pdf", width = 16.18, height = 10, units = "cm")


# print the summary
t<-to_plot %>% summarise(
  minimum = min(values),
  mean = mean(values),
  median = median(values),
  maximum = max(values))

kable(t, format = "latex", caption = "Summary statistics of the different heart rate errors for the different system settings", label = "tab:components_heart", align = "c")

```


# Comparing Devices
```{r devices,  echo=FALSE, warning=FALSE, message=FALSE}
# Define the main directory path
main_directory <- "../../data/sleep_lab/clean_data/esp"

# List all subdirectories (conditions) in the main directory
device_dirs <- list.dirs(main_directory, full.names = FALSE, recursive = FALSE)

# Initialize an data frame
device_data <- data_frame()

reference_data <- full_data %>% filter(filename=="CSI")

# Loop through condition directories
for (device_dir in device_dirs) {
  file <- file.path(main_directory, device_dir, "CSI.CSV")
  data <- read_csv(file)
  
  # deal with timestamp overflows
  indices <- which(data$local_timestamp[2:nrow(data)] < data$local_timestamp[1:(nrow(data)-1)])
  print(device_dir)
  print(indices)
  for(i in indices){
    data$local_timestamp[(i+1):nrow(data)] <- data$local_timestamp[(i+1):nrow(data)] + 4294967295
  }
  
  # Specify the output file name with the .svg extension
  # output_file <- "time_series_plot.pdf"
  # library(webshot)
  # # Export the dygraph plot as an SVG image
  # htmlwidgets::saveWidget(graph, file = output_file)
  file_type <- tools::file_path_sans_ext(basename(file))
  data <- data %>% mutate(pose = "none", condition = "none", device = device_dir)
  
  start_index <- c(14927, 25470, 34215, 39726, 47284, 55271, 60798, 64565)
  stop_index <- c(19242, 28543, 36099, 44131, 51867, 57690, 61955, 69201)
  pose <- c("back", "left", "stomach", "right", "back", "left", "stomach", "right")
  condition <- c("open", "open", "open", "open", "blanket", "blanket", "blanket", "blanket")
  
  start_is <- c()
  stop_is <- c()
  for(i in seq(8)){
    start_t <- reference_data$local_timestamp[start_index[i]]
    stop_t <- reference_data$local_timestamp[stop_index[i]]
    start_i <- which(data$local_timestamp > start_t)[1]-1
    stop_i <- which(data$local_timestamp > stop_t)[1]-1
    print(start_i)
    start_is <- c(start_is, start_i)
    stop_is <- c(stop_is, stop_i)
    print(stop_i)
    data$pose[start_i:stop_i] = pose[i]
    data$condition[start_i:stop_i] = condition[i]
  }
  # assign the conditions manually
  # order of poses: back, left, stomach, right
  # order of conditions: without blanket, with blanket

  device_data <- rbind(device_data, data)
}


start_index <- c(14927, 25470, 34215, 39726, 47284, 55271, 60798, 64565)
stop_index <- c(19242, 28543, 36099, 44131, 51867, 57690, 61955, 69201)
pose <- c("back", "left", "stomach", "right", "back", "left", "stomach", "right")
condition <- c("open", "open", "open", "open", "blanket", "blanket", "blanket", "blanket")

data <- device_data %>% filter(device == "left")


start_is[1]
plot$time[start_is[1]]

plot <- data  %>% mutate(time=local_timestamp/1000000) %>% select(time, sti)
dygraph(plot, main = device_dir, xlab = "time (in seconds)", ylab = "STI", group = "sti_plots") %>%
  dyOptions(drawPoints = TRUE, pointSize = 2) %>% 
  dyShading(from = plot$time[start_is[1]], to = plot$time[stop_is[1]], color = "#77FF77") %>% 
  dyShading(from = plot$time[start_is[2]], to = plot$time[stop_is[2]], color = "#FFE6E0") %>% 
  dyShading(from = plot$time[start_is[3]], to = plot$time[stop_is[3]], color = "#AAAAAA") %>% 
  dyShading(from = plot$time[start_is[4]], to = plot$time[stop_is[4]], color = "#266666") %>% 
  dyShading(from = plot$time[start_is[5]], to = plot$time[stop_is[5]], color = "#FF6666") %>% 
  dyShading(from = plot$time[start_is[6]], to = plot$time[stop_is[6]], color = "#BFFFFF") %>% 
  dyShading(from = plot$time[start_is[7]], to = plot$time[stop_is[7]], color = "#CFE000") %>% 
  dyShading(from = plot$time[start_is[8]], to = plot$time[stop_is[8]], color = "#4AAAAA") %>%
  dyRangeSelector()

data <- device_data %>% filter(device == "middle")

start_is <- c()
stop_is <- c()
for(i in seq(8)){
  start_t <- reference_data$local_timestamp[start_index[i]]
  stop_t <- reference_data$local_timestamp[stop_index[i]]
  start_i <- which(data$local_timestamp > start_t)[1]-1
  stop_i <- which(data$local_timestamp > stop_t)[1]-1
  print(start_i)
  start_is <- c(start_is, start_i)
  stop_is <- c(stop_is, stop_i)
  print(stop_i)
  data$pose[start_i:stop_i] = pose[i]
  data$condition[start_i:stop_i] = condition[i]
}
start_is[1]
plot$time[start_is[1]]

plot <- data  %>% mutate(time=local_timestamp/1000000) %>% select(time, sti)
dygraph(plot, main = device_dir, xlab = "time (in seconds)", ylab = "STI", group = "sti_plots") %>%
  dyOptions(drawPoints = TRUE, pointSize = 2) %>% 
  dyShading(from = plot$time[start_is[1]], to = plot$time[stop_is[1]], color = "#77FF77") %>% 
  dyShading(from = plot$time[start_is[2]], to = plot$time[stop_is[2]], color = "#FFE6E0") %>% 
  dyShading(from = plot$time[start_is[3]], to = plot$time[stop_is[3]], color = "#AAAAAA") %>% 
  dyShading(from = plot$time[start_is[4]], to = plot$time[stop_is[4]], color = "#266666") %>% 
  dyShading(from = plot$time[start_is[5]], to = plot$time[stop_is[5]], color = "#FF6666") %>% 
  dyShading(from = plot$time[start_is[6]], to = plot$time[stop_is[6]], color = "#BFFFFF") %>% 
  dyShading(from = plot$time[start_is[7]], to = plot$time[stop_is[7]], color = "#CFE000") %>% 
  dyShading(from = plot$time[start_is[8]], to = plot$time[stop_is[8]], color = "#4AAAAA") %>%
  dyRangeSelector()

data <- device_data %>% filter(device == "right")

start_is <- c()
stop_is <- c()
for(i in seq(8)){
  start_t <- reference_data$local_timestamp[start_index[i]]
  stop_t <- reference_data$local_timestamp[stop_index[i]]
  start_i <- which(data$local_timestamp > start_t)[1]-1
  stop_i <- which(data$local_timestamp > stop_t)[1]-1
  print(start_i)
  start_is <- c(start_is, start_i)
  stop_is <- c(stop_is, stop_i)
  print(stop_i)
  data$pose[start_i:stop_i] = pose[i]
  data$condition[start_i:stop_i] = condition[i]
}
start_is[1]
plot$time[start_is[1]]

plot <- data  %>% mutate(time=local_timestamp/1000000) %>% select(time, sti)
dygraph(plot, main = device_dir, xlab = "time (in seconds)", ylab = "STI", group = "sti_plots") %>%
  dyOptions(drawPoints = TRUE, pointSize = 2) %>% 
  dyShading(from = plot$time[start_is[1]], to = plot$time[stop_is[1]], color = "#77FF77") %>% 
  dyShading(from = plot$time[start_is[2]], to = plot$time[stop_is[2]], color = "#FFE6E0") %>% 
  dyShading(from = plot$time[start_is[3]], to = plot$time[stop_is[3]], color = "#AAAAAA") %>% 
  dyShading(from = plot$time[start_is[4]], to = plot$time[stop_is[4]], color = "#266666") %>% 
  dyShading(from = plot$time[start_is[5]], to = plot$time[stop_is[5]], color = "#FF6666") %>% 
  dyShading(from = plot$time[start_is[6]], to = plot$time[stop_is[6]], color = "#BFFFFF") %>% 
  dyShading(from = plot$time[start_is[7]], to = plot$time[stop_is[7]], color = "#CFE000") %>% 
  dyShading(from = plot$time[start_is[8]], to = plot$time[stop_is[8]], color = "#4AAAAA") %>%
  dyRangeSelector()

```

# STI captures breathing in some activities
```{r , echo=FALSE, warning=FALSE, message=FALSE}
options(digits.secs=4)
p <- "back"
c <- "open"
gt_ecg <- full_gt_ecg %>% filter(pose == p & condition == c)
gt_breath <- full_gt_breath_a %>% filter(pose == p & condition == c)

gt_ecg$time1 <- as.POSIXct(paste("1970-01-01", gt_ecg$time), tz = "UTC")
gt_ecg$time1 <- gt_ecg$time1 - (gt_ecg$time1[1] - as.POSIXct("1970-01-01 00:00:00.000", "UTC"))
                            
gt_breath$time1 <- as.POSIXct(paste("1970-01-01", gt_breath$time), tz = "UTC")
gt_breath$time1 <- gt_breath$time1 - (gt_breath$time1[1] - as.POSIXct("1970-01-01 00:00:00.000", "UTC"))

data <-  device_data %>% filter(pose == p & condition == c & device == "left")
data$local_timestamp = data$local_timestamp - data$local_timestamp[1]

ecg <- zoo(as.integer(gt_ecg$value), gt_ecg$time1)
sti <- zoo(as.double(data$sti), as.POSIXct(data$local_timestamp/1000000, "UTC", origin = "1970-01-01"))
filtered_heart <- zoo(as.double(data$filtered_heart), as.POSIXct(data$local_timestamp/1000000, "UTC", origin = "1970-01-01"))


eventData <- cbind(ecg, filtered_heart, sti)
eventData <- na.locf(eventData)

dygraph(eventData,xlab = "time") %>% 
  dyOptions(drawGrid = F) %>%
  dyAxis("y", independentTicks = TRUE, axisLabelFontSize=0) %>%
  dyAxis("y2", independentTicks = TRUE, axisLabelFontSize=0) %>%
  dySeries("ecg", axis=('y')) %>%
  dySeries("filtered_heart", axis=('y2')) %>%
  dySeries("sti", axis=('y2'), stepPlot=FALSE, label = "STI")


breath <- zoo(as.integer(gt_breath$value), gt_breath$time1)
sti <- zoo(as.double(data$sti), as.POSIXct(data$local_timestamp/1000000, "UTC", origin = "1970-01-01"))
filtered_breath <- zoo(as.double(data$filtered_breath), as.POSIXct(data$local_timestamp/1000000, "UTC", origin = "1970-01-01"))

eventData <- cbind(breath, filtered_breath, sti)
eventData <- na.locf(eventData)

dygraph(eventData, width = 2000, height = 800,xlab = "time") %>% 
  dyOptions(drawGrid = F,) %>%
  dyAxis("y", axisLabelFontSize=0) %>%
  dyAxis("y2", axisLabelFontSize=0) %>%
  dySeries("breath", axis=('y'), label = "RIP Abdomen") %>%
  dySeries("filtered_breath", axis=('y2'), stepPlot=FALSE, label = "Filtered breath amplitude") %>%
  dySeries("sti", axis=('y2'), stepPlot=FALSE, label = "STI")
  # dyShading(from = plot$time[0], to = plot$time[nrow(plot)], color = "#BFEFFF")

```

# Device comparison across all conditions
```{r,  echo=FALSE, warning=FALSE, message=FALSE}
complete_breath_results = data_frame()
complete_heart_results = data_frame()
for (c in c("open", "blanket")) {
  for (p in c("back", "left", "stomach", "right")) {
    data <- device_data %>% filter(pose == p & condition == c)
    breath_features <- data$breath_features
    breath_features <- data.frame(breath_features)
    
    breath_features <- breath_features %>%
      mutate(breath_features = substr(breath_features, 2, nchar(breath_features) - 1)) %>%
      mutate(breath_features = strsplit(breath_features, " ")) %>%
      mutate(breath_features = lapply(breath_features, function(x) as.numeric(x)))
    
    breath_features <- data.frame(matrix(unlist(breath_features$breath_features), ncol = 19, byrow = TRUE))
    colnames(breath_features) <- c("instantaneous_peak_rate","instantaneous_valley_rate","mean_peak_rate_over_window","mean_valley_rate_over_window","fft_rate_over_window","variance_of_peak_rate_in_window","variance_of_valley_rate_in_window","mean_up_stroke_length","mean_down_stroke_length","up_stroke_length_variance","down_stroke_length_variance","up_to_down_length_ratio","fractional_up_stroke_time","mean_up_stroke_amplitude","mean_down_stroke_amplitude","up_stroke_amplitude_variance","down_stroke_amplitude_variance","up_to_down_amplitude_ratio","fractional_up_stroke_amplitude")
    
    data$local_timestamp = data$local_timestamp - data$local_timestamp[1]
    breath_features <- cbind(breath_features, data$local_timestamp)
    breath_features <- breath_features %>% rename(time = `data$local_timestamp`) 
    breath_features <- cbind(breath_features, data$local_timestamp, data$device)
    breath_features <- breath_features %>% rename(device = `data$device`) 
    breath_features <- breath_features %>% mutate(time = as.POSIXct(breath_features$time/1000000, "UTC", origin = "1970-01-01"))
    
    heart_features <- data$heart_features
    heart_features <- data.frame(heart_features)
    
    heart_features <- heart_features %>%
      mutate(heart_features = substr(heart_features, 2, nchar(heart_features) - 1)) %>%
      mutate(heart_features = strsplit(heart_features, " ")) %>%
      mutate(heart_features = lapply(heart_features, function(x) as.numeric(x)))
    
    heart_features <- data.frame(matrix(unlist(heart_features$heart_features), ncol = 19, byrow = TRUE))
    colnames(heart_features) <- c("instantaneous_peak_rate","instantaneous_valley_rate","mean_peak_rate_over_window","mean_valley_rate_over_window","fft_rate_over_window","variance_of_peak_rate_in_window","variance_of_valley_rate_in_window","mean_up_stroke_length","mean_down_stroke_length","up_stroke_length_variance","down_stroke_length_variance","up_to_down_length_ratio","fractional_up_stroke_time","mean_up_stroke_amplitude","mean_down_stroke_amplitude","up_stroke_amplitude_variance","down_stroke_amplitude_variance","up_to_down_amplitude_ratio","fractional_up_stroke_amplitude")
    
    heart_features <- cbind(heart_features, data$local_timestamp)
    heart_features <- heart_features %>% rename(time = `data$local_timestamp`) 
    heart_features <- cbind(heart_features, data$local_timestamp, data$device)
    heart_features <- heart_features %>% rename(device = `data$device`) 
    heart_features <- heart_features %>% mutate(time = as.POSIXct(heart_features$time/1000000, "UTC", origin = "1970-01-01"))
    
    
    gt_breathing_rate <- full_gt_breathing_rate %>% filter(pose == p & condition == c)
    gt_breathing_rate$time <- as.POSIXct(paste("1970-01-01", gt_breathing_rate$time), tz = "UTC")
    gt_breathing_rate$time <- gt_breathing_rate$time - (gt_breathing_rate$time[1] - as.POSIXct("1970-01-01 00:00:00.000", "UTC"))
    gt_breathing_rate <- gt_breathing_rate %>% select(!type) %>% mutate(value = as.numeric(value))
    
    breath_results <- breath_features %>%
      full_join(gt_breathing_rate, by = "time")  %>%
      arrange(time)
    breath_results$value <- zoo::na.locf(breath_results$value, na.rm = F)
    breath_results$condition <- zoo::na.locf(breath_results$condition, na.rm = F)
    breath_results$pose <- zoo::na.locf(breath_results$pose, na.rm = F)
    breath_results <- breath_results %>% filter(!is.na(fft_rate_over_window))
    # remove initial rows where the reference is 0
    breath_results <- breath_results %>% filter(value != 0)
    
    # get the error and absolute error for breathing and heart rate
    breath_results <- breath_results %>% select(fft_rate_over_window, mean_peak_rate_over_window, value, time, condition, pose, device)
    colnames(breath_results) <- c("fft_rate_over_window", "mean_peak_rate_over_window", "gt_breathing_rate", "time", "condition", "pose", "device")
    
    
    gt_heart_rate <- full_gt_heart_rate %>% filter(pose == p & condition == c)
    gt_heart_rate$time <- as.POSIXct(paste("1970-01-01", gt_heart_rate$time), tz = "UTC")
    gt_heart_rate$time <- gt_heart_rate$time - (gt_heart_rate$time[1] - as.POSIXct("1970-01-01 00:00:00.000", "UTC"))
    gt_heart_rate <- gt_heart_rate %>% select(!type) %>% mutate(value = as.numeric(value))
    
    heart_results <- heart_features %>%
      full_join(gt_heart_rate, by = "time")  %>%
      arrange(time)
    heart_results$value <- zoo::na.locf(heart_results$value, na.rm = F)
    heart_results$condition <- zoo::na.locf(heart_results$condition, na.rm = F)
    heart_results$pose <- zoo::na.locf(heart_results$pose, na.rm = F)
    heart_results <- heart_results %>% filter(!is.na(fft_rate_over_window))
    # remove initial rows where the reference is 0
    heart_results <- heart_results %>% filter(value != 0)
    
    heart_results <- heart_results %>% select(fft_rate_over_window, mean_peak_rate_over_window, value, time, condition, pose, device)
    colnames(heart_results) <- c("fft_rate_over_window", "mean_peak_rate_over_window", "gt_heart_rate", "time", "condition", "pose", "device")
    
    breath_results <- breath_results %>%
      mutate(fft_error = fft_rate_over_window - gt_breathing_rate,
             abs_fft_error = abs(fft_rate_over_window - gt_breathing_rate),
             error = mean_peak_rate_over_window - gt_breathing_rate,
             abs_error = abs(mean_peak_rate_over_window - gt_breathing_rate))
    
    heart_results <- heart_results %>%
      mutate(fft_error = fft_rate_over_window - gt_heart_rate,
             abs_fft_error = abs(fft_rate_over_window - gt_heart_rate),
             error = mean_peak_rate_over_window - gt_heart_rate,
             abs_error = abs(mean_peak_rate_over_window - gt_heart_rate))
    
    complete_breath_results <- rbind(complete_breath_results, breath_results)
    complete_heart_results <- rbind(complete_heart_results, heart_results)
  }
}

# plot the results
to_plot <- breath_results %>% select(fft_error, abs_fft_error, error, abs_error, device) %>% pivot_longer(cols = c("fft_error", "abs_fft_error", "error", "abs_error"), names_to = "error_type", values_to = "values") %>% group_by(error_type, device)
p<-to_plot %>% ggplot() +
  geom_violin(aes(y=values, x=error_type, fill = device), width = 0.75, linewidth=0.2) +
  theme_light()+
  labs(fill = "Device")+
  ylab("Error (in bpm)")+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(),
        legend.justification = c(1, 1), 
        legend.position = c(1, 1))+
  scale_x_discrete(labels=c("abs_error"="absolute peak rate error", "abs_fft_error"="absolute fft rate error", "error"="peak rate error", "fft_error"="fft rate error")) +
  scale_fill_manual(values=c("left"="#61E8CB", "middle"="#E8A656", "right"="#4A62E8"))

p
ggsave("DeviceBreath.pdf", plot = p, device = "pdf", width = 16.18, height = 10, units = "cm")


# print the summary
t<-to_plot %>% summarise(
  minimum = min(values),
  mean = mean(values),
  median = median(values),
  maximum = max(values))
kable(t, format = "latex", caption = "Summary statistics of the different breathing rate errors for the different devices", label = "tab:devices_breath", align = "c")

# plot the results
to_plot <-  heart_results %>% select(fft_error, abs_fft_error, error, abs_error, device) %>% pivot_longer(cols = c("fft_error", "abs_fft_error", "error", "abs_error"), names_to = "error_type", values_to = "values") %>% group_by(error_type, device)
p<-to_plot %>% ggplot() +
  geom_violin(aes(y=values, x=error_type, fill = device), width = 0.75, linewidth=0.2) +
  theme_light()+
  labs(fill = "Device")+
  ylab("Error (in bpm)")+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(),
        legend.justification = c(1, 1), 
        legend.position = c(1, 1))+
  scale_x_discrete(labels=c("abs_error"="absolute peak rate error", "abs_fft_error"="absolute fft rate error", "error"="peak rate error", "fft_error"="fft rate error")) +
  scale_fill_manual(values=c("left"="#61E8CB", "middle"="#E8A656", "right"="#4A62E8"))

p
ggsave("DeviceHeart.pdf", plot = p, device = "pdf", width = 16.18, height = 10, units = "cm")


# print the summary
t<-to_plot %>% summarise(
  minimum = min(values),
  mean = mean(values),
  median = median(values),
  maximum = max(values))

kable(t, format = "latex", caption = "Summary statistics of the different heart rate errors for the different devices", label = "tab:devices_heart", align = "c")
```
